# Generated by Django 5.1.7 on 2025-05-26 05:26

import formularios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('form_id', models.CharField(default=formularios.models.generate_id, editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='Form ID')),
                ('modification_date', models.DateField(auto_now_add=True, null=True, verbose_name='Modification Date')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='formularios_subidos/', verbose_name='Archivo')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizado', 'Finalizado'), ('en curso', 'En curso')], default='pendiente', max_length=20, verbose_name='Status')),
            ],
        ),
    ]
