# Generated by Django 5.1.7 on 2025-05-26 05:26

import factorManager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id_factor', models.CharField(default=factorManager.models.generate_id_factor, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('ponderation', models.PositiveIntegerField(blank=True, null=True)),
                ('document_id', models.CharField(blank=True, max_length=80, null=True)),
                ('document_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['project__name', 'start_date', 'name'],
            },
        ),
    ]
