# Generated by Django 5.1.7 on 2025-05-26 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factorManager', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='projects.project'),
        ),
        migrations.AddField(
            model_name='factor',
            name='responsables',
            field=models.ManyToManyField(blank=True, related_name='responsible_factors', to=settings.AUTH_USER_MODEL, verbose_name='Responsables'),
        ),
    ]
