# Generated by Django 5.1.7 on 2025-05-26 05:26

import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id_project', models.CharField(default=projects.models._gen_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('folder_id', models.CharField(blank=True, max_length=100, null=True)),
                ('approved', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
