# Generated by Django 5.1.7 on 2025-05-26 05:26

import django.db.models.deletion
import strategicAnalysis.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMejoramiento',
            fields=[
                ('plan_id', models.CharField(default=strategicAnalysis.models.generate_id, editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='Plan ID')),
                ('title', models.CharField(default='Plan de Mejoramiento', max_length=255)),
                ('contenido_json', models.JSONField(blank=True, default=dict, help_text="Contenido del plan y notas en formato JSON. Ejemplo: {'plan_texto': '...', 'notas_texto': '...'}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan de Mejoramiento',
                'verbose_name_plural': 'Planes de Mejoramiento',
                'ordering': ['-update_at'],
            },
        ),
        migrations.CreateModel(
            name='Dofa',
            fields=[
                ('dofa_id', models.CharField(default=strategicAnalysis.models.generate_id, editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='DOFA ID')),
                ('fortalezas', models.JSONField(blank=True, default=dict, null=True, verbose_name='Fortalezas')),
                ('debilidades', models.JSONField(blank=True, default=dict, null=True, verbose_name='Debilidades')),
                ('oportunidades', models.JSONField(blank=True, default=dict, null=True, verbose_name='Oportunidades')),
                ('amenazas', models.JSONField(blank=True, default=dict, null=True, verbose_name='Amenazas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dofas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Análisis DOFA',
                'verbose_name_plural': 'Análisis DOFA',
                'ordering': ['-created_at'],
            },
        ),
    ]
