# Generated by Django 5.1.7 on 2025-05-26 05:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_url', models.URLField(help_text='Enlace compartible al PDF generado en Google Drive.', max_length=512, verbose_name='URL pública del PDF del Informe Final')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se generó el informe.', verbose_name='Fecha de Generación')),
                ('generated_by', models.ForeignKey(blank=True, help_text='Usuario que solicitó la generación del informe.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_final_reports', to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
            ],
            options={
                'verbose_name': 'Informe Final',
                'verbose_name_plural': 'Informes Finales',
                'ordering': ['-generated_at'],
            },
        ),
    ]
