# Generated by Django 5.1.7 on 2025-05-26 05:26

import database.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditationProcess',
            fields=[
                ('id_process', models.CharField(default=database.models.generate_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id_calendar', models.CharField(default=database.models.generate_id, editable=False, max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id_file', models.CharField(default=database.models.generate_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=10)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos_subidos/')),
                ('modification_date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('inactivo', 'Inactivo'), ('activo', 'Activo')], default='activo', max_length=20)),
                ('director_programa', models.CharField(blank=True, max_length=255, null=True)),
                ('object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('drive_link', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Enlace Google Drive')),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id_phase', models.CharField(default=database.models.generate_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id_version', models.CharField(default=database.models.generate_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ActiveAccreditationProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_process', models.ForeignKey(db_column='id_process', on_delete=django.db.models.deletion.CASCADE, to='database.accreditationprocess')),
            ],
        ),
    ]
