# Generated by Django 5.1.7 on 2025-05-26 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendar_create_event', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('database', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activeaccreditationprocess',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='file',
            name='id_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos', to='calendar_create_event.event', verbose_name='Evento Asociado (FK Directa)'),
        ),
        migrations.AddField(
            model_name='phase',
            name='id_process',
            field=models.ForeignKey(db_column='id_process', on_delete=django.db.models.deletion.CASCADE, to='database.accreditationprocess'),
        ),
        migrations.AddField(
            model_name='version',
            name='id_file',
            field=models.ForeignKey(db_column='id_file', on_delete=django.db.models.deletion.CASCADE, to='database.file'),
        ),
    ]
