# Generated by Django 5.1.7 on 2025-05-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lector', 'Lector'), ('comentador', 'Comentador'), ('editor', 'Editor')], max_length=12)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asignación de Factor',
                'verbose_name_plural': 'Asignaciones de Factores',
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lector', 'Lector'), ('comentador', 'Comentador'), ('editor', 'Editor')], max_length=12)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asignación de Proyecto',
                'verbose_name_plural': 'Asignaciones de Proyectos',
            },
        ),
    ]
