# Generated by Django 5.1.7 on 2025-05-26 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0002_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factorassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factor_assignments_as_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments_to_users', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments_as_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='factorassignment',
            unique_together={('factor', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='projectassignment',
            unique_together={('project', 'user')},
        ),
    ]
