# Generated by Django 5.1.7 on 2025-05-26 05:26

import django.db.models.deletion
import traitManager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factorManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id_trait', models.CharField(default=traitManager.models.generate_id_trait, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='factorManager.factor', verbose_name='Factor Asociado')),
            ],
            options={
                'verbose_name': 'Característica',
                'verbose_name_plural': 'Características',
                'ordering': ['name'],
            },
        ),
    ]
