# Generated by Django 5.1.7 on 2025-05-26 05:26

import aspectManager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id_aspect', models.CharField(default=aspectManager.models.generate_id_aspect, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (%)')),
                ('approved', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('is_completed', models.BooleanField(default=False)),
                ('acceptance_criteria', models.TextField(blank=True, null=True, verbose_name='Criterio de aceptación')),
                ('evaluation_rule', models.TextField(blank=True, null=True, verbose_name='Regla de evaluación')),
            ],
            options={
                'verbose_name': 'Aspecto',
                'verbose_name_plural': 'Aspectos',
                'ordering': ['name'],
            },
        ),
    ]
