# Generated by Django 5.1.7 on 2025-05-26 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aspectManager', '0001_initial'),
        ('traitManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspect',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspects', to='traitManager.trait', verbose_name='Característica'),
        ),
    ]
